/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProductCategory = IDL.Variant({
  'art' : IDL.Null,
  'music' : IDL.Null,
  'clothing' : IDL.Null,
  'cars' : IDL.Null,
  'food' : IDL.Null,
  'none' : IDL.Null,
  'furniture' : IDL.Null,
  'bikes' : IDL.Null,
  'books' : IDL.Null,
  'handmade' : IDL.Null,
  'services' : IDL.Null,
  'electronics' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ProductCreationData = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'category' : ProductCategory,
  'price' : IDL.Nat,
  'images' : IDL.Vec(ExternalBlob),
});
export const Time = IDL.Int;
export const ProductView = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'views' : IDL.Nat,
  'createdAt' : Time,
  'description' : IDL.Text,
  'seller' : IDL.Principal,
  'category' : ProductCategory,
  'price' : IDL.Nat,
  'images' : IDL.Vec(ExternalBlob),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createProduct' : IDL.Func([ProductCreationData], [IDL.Text], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(ProductView)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProductsBySeller' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ProductView)],
      ['query'],
    ),
  'getTopViewedProducts' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ProductView)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'incrementProductViews' : IDL.Func([IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'registerUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Bool],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProductCategory = IDL.Variant({
    'art' : IDL.Null,
    'music' : IDL.Null,
    'clothing' : IDL.Null,
    'cars' : IDL.Null,
    'food' : IDL.Null,
    'none' : IDL.Null,
    'furniture' : IDL.Null,
    'bikes' : IDL.Null,
    'books' : IDL.Null,
    'handmade' : IDL.Null,
    'services' : IDL.Null,
    'electronics' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ProductCreationData = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'category' : ProductCategory,
    'price' : IDL.Nat,
    'images' : IDL.Vec(ExternalBlob),
  });
  const Time = IDL.Int;
  const ProductView = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'views' : IDL.Nat,
    'createdAt' : Time,
    'description' : IDL.Text,
    'seller' : IDL.Principal,
    'category' : ProductCategory,
    'price' : IDL.Nat,
    'images' : IDL.Vec(ExternalBlob),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createProduct' : IDL.Func([ProductCreationData], [IDL.Text], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(ProductView)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProductsBySeller' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ProductView)],
        ['query'],
      ),
    'getTopViewedProducts' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ProductView)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'incrementProductViews' : IDL.Func([IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'registerUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Bool],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };